### ISSUE TITLE
depth=0 and multi value paths results

### ISSUE THREAD

**Issue by jensens** [plone/Products.ExtendedPathIndex#7]
This is an edge case, but multi valued paths are in general supported. pone.app.multilingualindexes creates an pathindex based on the translation group ids, so any path depth may contain more than one element. if searching with a zero depth, this breaks b/c of an optimization here. This can be made configurable with a minor effort. I'll propose a PR for this.
cc @thet

**Comment by thet** [comment]
Closed via: https://github.com/plone/Products.ExtendedPathIndex/pull/8
